[custom.all.js]
type   = "local"
path   = "js"
ipkg   = "js.ipkg"
test   = "test/test.ipkg"

[custom.all.dom]
type   = "local"
path   = "."
ipkg   = "dom.ipkg"

[custom.all.js-test]
type   = "local"
path   = "js/test"
ipkg   = "test.ipkg"

[custom.all.dom-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.quantifiers-extra]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-quantifiers-extra"
commit = "latest:main"
ipkg   = "quantifiers-extra.ipkg"
